version: '3'
services:
  node:
    build: .
    image: lizaveis/rest-service
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    depends_on:
      - postgres
    restart: on-failure
    environment:
      - PORT=${PORT}
  postgres:
    build: ./src/database/
    image: lizaveis/postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
   volumes:
      - ./data:/var/lib/postgresql/data
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
networks:
  default:
    name: rest-service-network